// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ecommerce.Models
{
    public partial class Carrelli
    {
        public Carrelli()
        {
            CarrelloProdottis = new HashSet<CarrelloProdotti>();
        }

        public int Id { get; set; }
        public int UtenteId { get; set; }

        public virtual Utenti Utente { get; set; }
        public virtual ICollection<CarrelloProdotti> CarrelloProdottis { get; set; }
    }
}