// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ecommerce.Models
{
    public partial class CarrelloProdotti
    {
        public int Id { get; set; }
        public int CarrelloId { get; set; }
        public int ProdottoId { get; set; }

        public virtual Carrelli Carrello { get; set; }
        public virtual Prodotti Prodotto { get; set; }
    }
}