// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ecommerce.Models
{
    public partial class Prodotti
    {
        public Prodotti()
        {
            CarrelloProdottis = new HashSet<CarrelloProdotti>();
        }

        public int Id { get; set; }
        public string Nome { get; set; }
        public decimal Prezzo { get; set; }
        public int QuantitaDisponibile { get; set; }

        public virtual ICollection<CarrelloProdotti> CarrelloProdottis { get; set; }
    }
}